### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by Babar-Bashir** [LangbaseInc/BaseAI#20]
### Description

I'm experiencing an issue where the site is accessible in Chrome but not in Firefox. Any suggestions on how to resolve this?
![image](https://github.com/user-attachments/assets/74226317-e5ac-43b4-b169-8bbac6758f06)

**Comment by msaaddev** [comment]
I just tested it in Firefox and it's working.

![screenshot-2024-10-01-at-07 43 22AM@2x](https://github.com/user-attachments/assets/59fd7f20-e58b-4cad-a988-9c4ed4303a6a)

Can you please try clearing your browser cache?

**Comment by Babar-Bashir** [comment]
Great, it's working now. Thanks!
